//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnstuckMEServerGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.Servers = new HashSet<Server>();
        }
    
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string EmailCredentials { get; set; }
    
        public virtual SchoolLogo SchoolLogo { get; set; }
        public virtual ICollection<Server> Servers { get; set; }
    }
}
