//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnstuckMEInterfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllStickers_View
    {
        public string Student { get; set; }
        public string EmailAddress { get; set; }
        public string Course { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<double> MinimumStarRanking { get; set; }
        public System.DateTime SubmitTime { get; set; }
        public System.DateTime Timeout { get; set; }
    }
}
