//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnstuckMEServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public Chat()
        {
            this.Files = new HashSet<File>();
            this.Messages = new HashSet<Message>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int ChatID { get; set; }
    
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
