//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnstuckMEServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Stickers = new HashSet<Sticker>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int ClassID { get; set; }
        public string CourseName { get; set; }
        public string CourseCode { get; set; }
        public short CourseNumber { get; set; }
    
        public virtual ICollection<Sticker> Stickers { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
