//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnstuckMEServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileID { get; set; }
        public int ChatID { get; set; }
        public byte[] FileData { get; set; }
        public int SentBy { get; set; }
        public System.DateTime SentTime { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
