//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace UnstuckMEServer
{
    public partial class Review
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Review()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public int ReviewID { get; set; }
        public int StickerID { get; set; }
        public int ReviewerID { get; set; }
        public Nullable<double> StarRanking { get; set; }
        public string Description { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual Sticker Sticker { get; set; }
    }
}
