//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnstuckMEServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class UnstuckME_DBEntities : DbContext
    {
        public UnstuckME_DBEntities()
            : base("name=UnstuckME_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Chat> Chats { get; set; }
        public DbSet<Class> Classes { get; set; }
        public DbSet<Friend> Friends { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<OfficialMentor> OfficialMentors { get; set; }
        public DbSet<Picture> Pictures { get; set; }
        public DbSet<Report> Reports { get; set; }
        public DbSet<Review> Reviews { get; set; }
        public DbSet<ServerAdmin> ServerAdmins { get; set; }
        public DbSet<Sticker> Stickers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
    
        public virtual int AddFriend(Nullable<int> currentUserID, Nullable<int> newFriendUserID)
        {
            var currentUserIDParameter = currentUserID.HasValue ?
                new ObjectParameter("CurrentUserID", currentUserID) :
                new ObjectParameter("CurrentUserID", typeof(int));
    
            var newFriendUserIDParameter = newFriendUserID.HasValue ?
                new ObjectParameter("NewFriendUserID", newFriendUserID) :
                new ObjectParameter("NewFriendUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddFriend", currentUserIDParameter, newFriendUserIDParameter);
        }
    
        public virtual int AddOrgToSticker(Nullable<int> stickerID, Nullable<int> organizationID)
        {
            var stickerIDParameter = stickerID.HasValue ?
                new ObjectParameter("StickerID", stickerID) :
                new ObjectParameter("StickerID", typeof(int));
    
            var organizationIDParameter = organizationID.HasValue ?
                new ObjectParameter("OrganizationID", organizationID) :
                new ObjectParameter("OrganizationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddOrgToSticker", stickerIDParameter, organizationIDParameter);
        }
    
        public virtual int AddStudentStarRankToUser(Nullable<int> userID, Nullable<double> starRanking)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var starRankingParameter = starRanking.HasValue ?
                new ObjectParameter("StarRanking", starRanking) :
                new ObjectParameter("StarRanking", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddStudentStarRankToUser", userIDParameter, starRankingParameter);
        }
    
        public virtual int AddTutorStarRankToUser(Nullable<int> userID, Nullable<double> starRanking)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var starRankingParameter = starRanking.HasValue ?
                new ObjectParameter("StarRanking", starRanking) :
                new ObjectParameter("StarRanking", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddTutorStarRankToUser", userIDParameter, starRankingParameter);
        }
    
        public virtual ObjectResult<AdminPullReportsForOptionalUser_Result> AdminPullReportsForOptionalUser(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdminPullReportsForOptionalUser_Result>("AdminPullReportsForOptionalUser", useridParameter);
        }
    
        public virtual int CheckIfAChatBetweenTwoUsersExists(Nullable<int> studentID, Nullable<int> tutorID)
        {
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("studentID", studentID) :
                new ObjectParameter("studentID", typeof(int));
    
            var tutorIDParameter = tutorID.HasValue ?
                new ObjectParameter("tutorID", tutorID) :
                new ObjectParameter("tutorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CheckIfAChatBetweenTwoUsersExists", studentIDParameter, tutorIDParameter);
        }
    
        public virtual int ClearReviewDescriptionByReviewID(Nullable<int> reviewID)
        {
            var reviewIDParameter = reviewID.HasValue ?
                new ObjectParameter("ReviewID", reviewID) :
                new ObjectParameter("ReviewID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearReviewDescriptionByReviewID", reviewIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CreateChat(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CreateChat", userIDParameter);
        }
    
        public virtual int CreateMentorOrganization(string organizationName)
        {
            var organizationNameParameter = organizationName != null ?
                new ObjectParameter("OrganizationName", organizationName) :
                new ObjectParameter("OrganizationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateMentorOrganization", organizationNameParameter);
        }
    
        public virtual int CreateNewAdminUser(string firstName, string lastName, string emailAddress, string password, string salt)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var saltParameter = salt != null ?
                new ObjectParameter("Salt", salt) :
                new ObjectParameter("Salt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateNewAdminUser", firstNameParameter, lastNameParameter, emailAddressParameter, passwordParameter, saltParameter);
        }
    
        public virtual int CreateNewClass(string courseName, string courseCode, Nullable<short> courseNumber)
        {
            var courseNameParameter = courseName != null ?
                new ObjectParameter("CourseName", courseName) :
                new ObjectParameter("CourseName", typeof(string));
    
            var courseCodeParameter = courseCode != null ?
                new ObjectParameter("CourseCode", courseCode) :
                new ObjectParameter("CourseCode", typeof(string));
    
            var courseNumberParameter = courseNumber.HasValue ?
                new ObjectParameter("CourseNumber", courseNumber) :
                new ObjectParameter("CourseNumber", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateNewClass", courseNameParameter, courseCodeParameter, courseNumberParameter);
        }
    
        public virtual int CreateNewUser(string firstName, string lastName, string emailAddress, string password, string salt)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var saltParameter = salt != null ?
                new ObjectParameter("Salt", salt) :
                new ObjectParameter("Salt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateNewUser", firstNameParameter, lastNameParameter, emailAddressParameter, passwordParameter, saltParameter);
        }
    
        public virtual int CreateReport(string reportDescription, Nullable<int> flaggerID, Nullable<int> reviewID)
        {
            var reportDescriptionParameter = reportDescription != null ?
                new ObjectParameter("ReportDescription", reportDescription) :
                new ObjectParameter("ReportDescription", typeof(string));
    
            var flaggerIDParameter = flaggerID.HasValue ?
                new ObjectParameter("FlaggerID", flaggerID) :
                new ObjectParameter("FlaggerID", typeof(int));
    
            var reviewIDParameter = reviewID.HasValue ?
                new ObjectParameter("ReviewID", reviewID) :
                new ObjectParameter("ReviewID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateReport", reportDescriptionParameter, flaggerIDParameter, reviewIDParameter);
        }
    
        public virtual int CreateReview(Nullable<int> stickerID, Nullable<int> reviewerID, Nullable<double> starRanking, string description)
        {
            var stickerIDParameter = stickerID.HasValue ?
                new ObjectParameter("StickerID", stickerID) :
                new ObjectParameter("StickerID", typeof(int));
    
            var reviewerIDParameter = reviewerID.HasValue ?
                new ObjectParameter("ReviewerID", reviewerID) :
                new ObjectParameter("ReviewerID", typeof(int));
    
            var starRankingParameter = starRanking.HasValue ?
                new ObjectParameter("StarRanking", starRanking) :
                new ObjectParameter("StarRanking", typeof(double));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateReview", stickerIDParameter, reviewerIDParameter, starRankingParameter, descriptionParameter);
        }
    
        public virtual int CreateServerAdmin(string firstName, string lastName, string emailAddress, string password, string salt)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var saltParameter = salt != null ?
                new ObjectParameter("Salt", salt) :
                new ObjectParameter("Salt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateServerAdmin", firstNameParameter, lastNameParameter, emailAddressParameter, passwordParameter, saltParameter);
        }
    
        public virtual int CreateSticker(string problemDescription, Nullable<int> classID, Nullable<int> studentID, Nullable<double> minimumStarRanking, Nullable<int> timeout)
        {
            var problemDescriptionParameter = problemDescription != null ?
                new ObjectParameter("ProblemDescription", problemDescription) :
                new ObjectParameter("ProblemDescription", typeof(string));
    
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(int));
    
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(int));
    
            var minimumStarRankingParameter = minimumStarRanking.HasValue ?
                new ObjectParameter("MinimumStarRanking", minimumStarRanking) :
                new ObjectParameter("MinimumStarRanking", typeof(double));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("Timeout", timeout) :
                new ObjectParameter("Timeout", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateSticker", problemDescriptionParameter, classIDParameter, studentIDParameter, minimumStarRankingParameter, timeoutParameter);
        }
    
        public virtual int DeleteClassByClassID(Nullable<int> classID)
        {
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteClassByClassID", classIDParameter);
        }
    
        public virtual int DeleteFriend(Nullable<int> currentUserID, Nullable<int> targetFriendUserID)
        {
            var currentUserIDParameter = currentUserID.HasValue ?
                new ObjectParameter("CurrentUserID", currentUserID) :
                new ObjectParameter("CurrentUserID", typeof(int));
    
            var targetFriendUserIDParameter = targetFriendUserID.HasValue ?
                new ObjectParameter("TargetFriendUserID", targetFriendUserID) :
                new ObjectParameter("TargetFriendUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteFriend", currentUserIDParameter, targetFriendUserIDParameter);
        }
    
        public virtual int DeleteMentorOrganizationByMentorID(Nullable<int> mentorID)
        {
            var mentorIDParameter = mentorID.HasValue ?
                new ObjectParameter("MentorID", mentorID) :
                new ObjectParameter("MentorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteMentorOrganizationByMentorID", mentorIDParameter);
        }
    
        public virtual int DeleteMessageByMessageID(Nullable<int> messageID)
        {
            var messageIDParameter = messageID.HasValue ?
                new ObjectParameter("MessageID", messageID) :
                new ObjectParameter("MessageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteMessageByMessageID", messageIDParameter);
        }
    
        public virtual int DeleteReportByReportID(Nullable<int> reportID)
        {
            var reportIDParameter = reportID.HasValue ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteReportByReportID", reportIDParameter);
        }
    
        public virtual int DeleteReviewByReviewID(Nullable<int> reviewID)
        {
            var reviewIDParameter = reviewID.HasValue ?
                new ObjectParameter("ReviewID", reviewID) :
                new ObjectParameter("ReviewID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteReviewByReviewID", reviewIDParameter);
        }
    
        public virtual int DeleteServerAdmin(Nullable<int> adminID)
        {
            var adminIDParameter = adminID.HasValue ?
                new ObjectParameter("AdminID", adminID) :
                new ObjectParameter("AdminID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteServerAdmin", adminIDParameter);
        }
    
        public virtual int DeleteStickerByStickerID(Nullable<int> stickerID)
        {
            var stickerIDParameter = stickerID.HasValue ?
                new ObjectParameter("StickerID", stickerID) :
                new ObjectParameter("StickerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteStickerByStickerID", stickerIDParameter);
        }
    
        public virtual int DeleteUserFromClass(Nullable<int> userID, Nullable<int> classID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUserFromClass", userIDParameter, classIDParameter);
        }
    
        public virtual int DeleteUserPictureByUserID(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUserPictureByUserID", userIDParameter);
        }
    
        public virtual int DeleteUserProfileByUserID(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUserProfileByUserID", userIDParameter);
        }
    
        public virtual ObjectResult<GetActiveStickers_ClassASC_Result> GetActiveStickers_ClassASC(Nullable<int> loggedin_user, Nullable<double> starrank, Nullable<short> startrow, Nullable<short> endrow, Nullable<int> userid, Nullable<int> classid)
        {
            var loggedin_userParameter = loggedin_user.HasValue ?
                new ObjectParameter("loggedin_user", loggedin_user) :
                new ObjectParameter("loggedin_user", typeof(int));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var classidParameter = classid.HasValue ?
                new ObjectParameter("classid", classid) :
                new ObjectParameter("classid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveStickers_ClassASC_Result>("GetActiveStickers_ClassASC", loggedin_userParameter, starrankParameter, startrowParameter, endrowParameter, useridParameter, classidParameter);
        }
    
        public virtual ObjectResult<GetActiveStickers_ClassDESC_Result> GetActiveStickers_ClassDESC(Nullable<int> loggedin_user, Nullable<double> starrank, Nullable<short> startrow, Nullable<short> endrow, Nullable<int> userid, Nullable<int> classid)
        {
            var loggedin_userParameter = loggedin_user.HasValue ?
                new ObjectParameter("loggedin_user", loggedin_user) :
                new ObjectParameter("loggedin_user", typeof(int));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var classidParameter = classid.HasValue ?
                new ObjectParameter("classid", classid) :
                new ObjectParameter("classid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveStickers_ClassDESC_Result>("GetActiveStickers_ClassDESC", loggedin_userParameter, starrankParameter, startrowParameter, endrowParameter, useridParameter, classidParameter);
        }
    
        public virtual ObjectResult<GetActiveStickersWithOrganization_ClassDESC_Result> GetActiveStickersWithOrganization_ClassDESC(Nullable<int> loggedin_user, Nullable<int> organization, Nullable<double> starrank, Nullable<short> startrow, Nullable<short> endrow, Nullable<int> userid, Nullable<int> classid)
        {
            var loggedin_userParameter = loggedin_user.HasValue ?
                new ObjectParameter("loggedin_user", loggedin_user) :
                new ObjectParameter("loggedin_user", typeof(int));
    
            var organizationParameter = organization.HasValue ?
                new ObjectParameter("organization", organization) :
                new ObjectParameter("organization", typeof(int));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var classidParameter = classid.HasValue ?
                new ObjectParameter("classid", classid) :
                new ObjectParameter("classid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveStickersWithOrganization_ClassDESC_Result>("GetActiveStickersWithOrganization_ClassDESC", loggedin_userParameter, organizationParameter, starrankParameter, startrowParameter, endrowParameter, useridParameter, classidParameter);
        }
    
        public virtual ObjectResult<GetActiveStickersWithOrganization_OrgClassASC_Result> GetActiveStickersWithOrganization_OrgClassASC(Nullable<int> loggedin_user, Nullable<int> organization, Nullable<double> starrank, Nullable<short> startrow, Nullable<short> endrow, Nullable<int> userid, Nullable<int> classid)
        {
            var loggedin_userParameter = loggedin_user.HasValue ?
                new ObjectParameter("loggedin_user", loggedin_user) :
                new ObjectParameter("loggedin_user", typeof(int));
    
            var organizationParameter = organization.HasValue ?
                new ObjectParameter("organization", organization) :
                new ObjectParameter("organization", typeof(int));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var classidParameter = classid.HasValue ?
                new ObjectParameter("classid", classid) :
                new ObjectParameter("classid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveStickersWithOrganization_OrgClassASC_Result>("GetActiveStickersWithOrganization_OrgClassASC", loggedin_userParameter, organizationParameter, starrankParameter, startrowParameter, endrowParameter, useridParameter, classidParameter);
        }
    
        public virtual ObjectResult<GetActiveStickersWithOrganization_OrgClassDESC_Result> GetActiveStickersWithOrganization_OrgClassDESC(Nullable<int> loggedin_user, Nullable<int> organization, Nullable<double> starrank, Nullable<short> startrow, Nullable<short> endrow, Nullable<int> userid, Nullable<int> classid)
        {
            var loggedin_userParameter = loggedin_user.HasValue ?
                new ObjectParameter("loggedin_user", loggedin_user) :
                new ObjectParameter("loggedin_user", typeof(int));
    
            var organizationParameter = organization.HasValue ?
                new ObjectParameter("organization", organization) :
                new ObjectParameter("organization", typeof(int));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var classidParameter = classid.HasValue ?
                new ObjectParameter("classid", classid) :
                new ObjectParameter("classid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveStickersWithOrganization_OrgClassDESC_Result>("GetActiveStickersWithOrganization_OrgClassDESC", loggedin_userParameter, organizationParameter, starrankParameter, startrowParameter, endrowParameter, useridParameter, classidParameter);
        }
    
        public virtual ObjectResult<GetActiveStickersWithOrganization_OrgDESC_Result> GetActiveStickersWithOrganization_OrgDESC(Nullable<int> loggedin_user, Nullable<int> organization, Nullable<double> starrank, Nullable<short> startrow, Nullable<short> endrow, Nullable<int> userid, Nullable<int> classid)
        {
            var loggedin_userParameter = loggedin_user.HasValue ?
                new ObjectParameter("loggedin_user", loggedin_user) :
                new ObjectParameter("loggedin_user", typeof(int));
    
            var organizationParameter = organization.HasValue ?
                new ObjectParameter("organization", organization) :
                new ObjectParameter("organization", typeof(int));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var classidParameter = classid.HasValue ?
                new ObjectParameter("classid", classid) :
                new ObjectParameter("classid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveStickersWithOrganization_OrgDESC_Result>("GetActiveStickersWithOrganization_OrgDESC", loggedin_userParameter, organizationParameter, starrankParameter, startrowParameter, endrowParameter, useridParameter, classidParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetAllChatsAUserIsPartOF(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetAllChatsAUserIsPartOF", useridParameter);
        }
    
        public virtual ObjectResult<GetAllMembersOfAChat_Result> GetAllMembersOfAChat(Nullable<int> chatid)
        {
            var chatidParameter = chatid.HasValue ?
                new ObjectParameter("chatid", chatid) :
                new ObjectParameter("chatid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllMembersOfAChat_Result>("GetAllMembersOfAChat", chatidParameter);
        }
    
        public virtual ObjectResult<GetAllOrganizations_Result> GetAllOrganizations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllOrganizations_Result>("GetAllOrganizations");
        }
    
        public virtual ObjectResult<GetAllResolvedOrTimedOutStickers_Result> GetAllResolvedOrTimedOutStickers(Nullable<int> userID, Nullable<short> startrow, Nullable<short> endrow, Nullable<double> starrank, Nullable<int> classID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("classID", classID) :
                new ObjectParameter("classID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllResolvedOrTimedOutStickers_Result>("GetAllResolvedOrTimedOutStickers", userIDParameter, startrowParameter, endrowParameter, starrankParameter, classIDParameter);
        }
    
        public virtual ObjectResult<GetAllStickers_Result> GetAllStickers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllStickers_Result>("GetAllStickers");
        }
    
        public virtual ObjectResult<GetAllStudentReviews_Result> GetAllStudentReviews()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllStudentReviews_Result>("GetAllStudentReviews");
        }
    
        public virtual ObjectResult<GetAllTutorReviews_Result> GetAllTutorReviews()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllTutorReviews_Result>("GetAllTutorReviews");
        }
    
        public virtual ObjectResult<GetAllUsersInAnOrganization_Result> GetAllUsersInAnOrganization(Nullable<int> orgid)
        {
            var orgidParameter = orgid.HasValue ?
                new ObjectParameter("orgid", orgid) :
                new ObjectParameter("orgid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllUsersInAnOrganization_Result>("GetAllUsersInAnOrganization", orgidParameter);
        }
    
        public virtual ObjectResult<GetChatMessages_Result> GetChatMessages(Nullable<int> chatid, Nullable<short> startrow, Nullable<short> endrow)
        {
            var chatidParameter = chatid.HasValue ?
                new ObjectParameter("chatid", chatid) :
                new ObjectParameter("chatid", typeof(int));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetChatMessages_Result>("GetChatMessages", chatidParameter, startrowParameter, endrowParameter);
        }
    
        public virtual ObjectResult<string> GetCourseCodes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetCourseCodes");
        }
    
        public virtual ObjectResult<Nullable<int>> GetCourseIDByCodeAndNumber(string code, Nullable<short> number)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var numberParameter = number.HasValue ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetCourseIDByCodeAndNumber", codeParameter, numberParameter);
        }
    
        public virtual ObjectResult<string> GetCourseNameByCodeAndNumber(string code, Nullable<short> number)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var numberParameter = number.HasValue ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetCourseNameByCodeAndNumber", codeParameter, numberParameter);
        }
    
        public virtual ObjectResult<Nullable<short>> GetCourseNumberByCourseCode(string code)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<short>>("GetCourseNumberByCourseCode", codeParameter);
        }
    
        public virtual ObjectResult<GetDisplayNameAndEmail_Result> GetDisplayNameAndEmail(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDisplayNameAndEmail_Result>("GetDisplayNameAndEmail", useridParameter);
        }
    
        public virtual ObjectResult<byte[]> GetProfilePicture(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("GetProfilePicture", useridParameter);
        }
    
        public virtual ObjectResult<GetReportsSubmittedByUser_Result> GetReportsSubmittedByUser(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReportsSubmittedByUser_Result>("GetReportsSubmittedByUser", useridParameter);
        }
    
        public virtual ObjectResult<GetResolvedStickers_ClassASC_Result> GetResolvedStickers_ClassASC(Nullable<double> starrank, Nullable<short> startrow, Nullable<short> endrow, Nullable<int> userid, Nullable<int> classid)
        {
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var classidParameter = classid.HasValue ?
                new ObjectParameter("classid", classid) :
                new ObjectParameter("classid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetResolvedStickers_ClassASC_Result>("GetResolvedStickers_ClassASC", starrankParameter, startrowParameter, endrowParameter, useridParameter, classidParameter);
        }
    
        public virtual ObjectResult<GetResolvedStickers_ClassDESC_Result> GetResolvedStickers_ClassDESC(Nullable<double> starrank, Nullable<short> startrow, Nullable<short> endrow, Nullable<int> userid, Nullable<int> classid)
        {
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var classidParameter = classid.HasValue ?
                new ObjectParameter("classid", classid) :
                new ObjectParameter("classid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetResolvedStickers_ClassDESC_Result>("GetResolvedStickers_ClassDESC", starrankParameter, startrowParameter, endrowParameter, useridParameter, classidParameter);
        }
    
        public virtual ObjectResult<GetTimedOutStickers_ClassASC_Result> GetTimedOutStickers_ClassASC(Nullable<double> starrank, Nullable<short> startrow, Nullable<short> endrow, Nullable<int> userid, Nullable<int> classid)
        {
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var classidParameter = classid.HasValue ?
                new ObjectParameter("classid", classid) :
                new ObjectParameter("classid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTimedOutStickers_ClassASC_Result>("GetTimedOutStickers_ClassASC", starrankParameter, startrowParameter, endrowParameter, useridParameter, classidParameter);
        }
    
        public virtual ObjectResult<GetTimedOutStickers_ClassDESC_Result> GetTimedOutStickers_ClassDESC(Nullable<double> starrank, Nullable<short> startrow, Nullable<short> endrow, Nullable<int> userid, Nullable<int> classid)
        {
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var classidParameter = classid.HasValue ?
                new ObjectParameter("classid", classid) :
                new ObjectParameter("classid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTimedOutStickers_ClassDESC_Result>("GetTimedOutStickers_ClassDESC", starrankParameter, startrowParameter, endrowParameter, useridParameter, classidParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> GetUserAvgStudentStarRank(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("GetUserAvgStudentStarRank", useridParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> GetUserAvgTutorStarRank(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("GetUserAvgTutorStarRank", useridParameter);
        }
    
        public virtual ObjectResult<GetUserClasses_Result> GetUserClasses(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserClasses_Result>("GetUserClasses", useridParameter);
        }
    
        public virtual ObjectResult<GetUserFriends_Result> GetUserFriends(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserFriends_Result>("GetUserFriends", useridParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetUserID(string useremail)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetUserID", useremailParameter);
        }
    
        public virtual ObjectResult<GetUserInfo_Result> GetUserInfo(Nullable<int> userid, string email)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserInfo_Result>("GetUserInfo", useridParameter, emailParameter);
        }
    
        public virtual ObjectResult<string> GetUserOrganizations(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUserOrganizations", useridParameter);
        }
    
        public virtual ObjectResult<GetUserPasswordAndSalt_Result> GetUserPasswordAndSalt(string emailAddress)
        {
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserPasswordAndSalt_Result>("GetUserPasswordAndSalt", emailAddressParameter);
        }
    
        public virtual ObjectResult<GetUsersInAClass_Result> GetUsersInAClass(Nullable<int> classid)
        {
            var classidParameter = classid.HasValue ?
                new ObjectParameter("classid", classid) :
                new ObjectParameter("classid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsersInAClass_Result>("GetUsersInAClass", classidParameter);
        }
    
        public virtual ObjectResult<GetUsersOverallStarRank_Result> GetUsersOverallStarRank(Nullable<double> starrank)
        {
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsersOverallStarRank_Result>("GetUsersOverallStarRank", starrankParameter);
        }
    
        public virtual ObjectResult<GetUserStudentReviews_RankASC_Result> GetUserStudentReviews_RankASC(Nullable<int> userid, Nullable<short> startrow, Nullable<short> endrow, Nullable<double> starrank)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserStudentReviews_RankASC_Result>("GetUserStudentReviews_RankASC", useridParameter, startrowParameter, endrowParameter, starrankParameter);
        }
    
        public virtual ObjectResult<GetUserStudentReviews_RankDESC_Result> GetUserStudentReviews_RankDESC(Nullable<int> userid, Nullable<short> startrow, Nullable<short> endrow, Nullable<double> starrank)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserStudentReviews_RankDESC_Result>("GetUserStudentReviews_RankDESC", useridParameter, startrowParameter, endrowParameter, starrankParameter);
        }
    
        public virtual ObjectResult<GetUserSubmittedStickers_ClassASC_Result> GetUserSubmittedStickers_ClassASC(Nullable<int> userID, Nullable<short> startrow, Nullable<short> endrow, Nullable<double> starrank, Nullable<int> classID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("classID", classID) :
                new ObjectParameter("classID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserSubmittedStickers_ClassASC_Result>("GetUserSubmittedStickers_ClassASC", userIDParameter, startrowParameter, endrowParameter, starrankParameter, classIDParameter);
        }
    
        public virtual ObjectResult<GetUserSubmittedStickers_ClassDESC_Result> GetUserSubmittedStickers_ClassDESC(Nullable<int> userID, Nullable<short> startrow, Nullable<short> endrow, Nullable<double> starrank, Nullable<int> classID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("classID", classID) :
                new ObjectParameter("classID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserSubmittedStickers_ClassDESC_Result>("GetUserSubmittedStickers_ClassDESC", userIDParameter, startrowParameter, endrowParameter, starrankParameter, classIDParameter);
        }
    
        public virtual ObjectResult<GetUserTutoredStickers_ClassASC_Result> GetUserTutoredStickers_ClassASC(Nullable<int> userID, Nullable<short> startrow, Nullable<short> endrow, Nullable<double> starrank, Nullable<int> classID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("classID", classID) :
                new ObjectParameter("classID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserTutoredStickers_ClassASC_Result>("GetUserTutoredStickers_ClassASC", userIDParameter, startrowParameter, endrowParameter, starrankParameter, classIDParameter);
        }
    
        public virtual ObjectResult<GetUserTutoredStickers_ClassDESC_Result> GetUserTutoredStickers_ClassDESC(Nullable<int> userID, Nullable<short> startrow, Nullable<short> endrow, Nullable<double> starrank, Nullable<int> classID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("classID", classID) :
                new ObjectParameter("classID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserTutoredStickers_ClassDESC_Result>("GetUserTutoredStickers_ClassDESC", userIDParameter, startrowParameter, endrowParameter, starrankParameter, classIDParameter);
        }
    
        public virtual ObjectResult<GetUserTutorReviews_RankASC_Result> GetUserTutorReviews_RankASC(Nullable<int> userid, Nullable<short> startrow, Nullable<short> endrow, Nullable<double> starrank)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserTutorReviews_RankASC_Result>("GetUserTutorReviews_RankASC", useridParameter, startrowParameter, endrowParameter, starrankParameter);
        }
    
        public virtual ObjectResult<GetUserTutorReviews_RankDESC_Result> GetUserTutorReviews_RankDESC(Nullable<int> userid, Nullable<short> startrow, Nullable<short> endrow, Nullable<double> starrank)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var startrowParameter = startrow.HasValue ?
                new ObjectParameter("startrow", startrow) :
                new ObjectParameter("startrow", typeof(short));
    
            var endrowParameter = endrow.HasValue ?
                new ObjectParameter("endrow", endrow) :
                new ObjectParameter("endrow", typeof(short));
    
            var starrankParameter = starrank.HasValue ?
                new ObjectParameter("starrank", starrank) :
                new ObjectParameter("starrank", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserTutorReviews_RankDESC_Result>("GetUserTutorReviews_RankDESC", useridParameter, startrowParameter, endrowParameter, starrankParameter);
        }
    
        public virtual int InsertMessage(Nullable<int> chatID, string message, string filePath, Nullable<bool> isFile, Nullable<int> userID)
        {
            var chatIDParameter = chatID.HasValue ?
                new ObjectParameter("ChatID", chatID) :
                new ObjectParameter("ChatID", typeof(int));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("FilePath", filePath) :
                new ObjectParameter("FilePath", typeof(string));
    
            var isFileParameter = isFile.HasValue ?
                new ObjectParameter("IsFile", isFile) :
                new ObjectParameter("IsFile", typeof(bool));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertMessage", chatIDParameter, messageParameter, filePathParameter, isFileParameter, userIDParameter);
        }
    
        public virtual int InsertStudentIntoClass(Nullable<int> userID, Nullable<int> classID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStudentIntoClass", userIDParameter, classIDParameter);
        }
    
        public virtual int InsertUserIntoChat(Nullable<int> userID, Nullable<int> chatID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var chatIDParameter = chatID.HasValue ?
                new ObjectParameter("ChatID", chatID) :
                new ObjectParameter("ChatID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertUserIntoChat", userIDParameter, chatIDParameter);
        }
    
        public virtual int InsertUserIntoMentorProgram(Nullable<int> userID, Nullable<int> mentorID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var mentorIDParameter = mentorID.HasValue ?
                new ObjectParameter("MentorID", mentorID) :
                new ObjectParameter("MentorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertUserIntoMentorProgram", userIDParameter, mentorIDParameter);
        }
    
        public virtual int MarkStickerAsResolved(Nullable<int> stickerID)
        {
            var stickerIDParameter = stickerID.HasValue ?
                new ObjectParameter("StickerID", stickerID) :
                new ObjectParameter("StickerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MarkStickerAsResolved", stickerIDParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int UpdateCourseCodeByClassID(Nullable<int> classID, string courseCode)
        {
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(int));
    
            var courseCodeParameter = courseCode != null ?
                new ObjectParameter("CourseCode", courseCode) :
                new ObjectParameter("CourseCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCourseCodeByClassID", classIDParameter, courseCodeParameter);
        }
    
        public virtual int UpdateCourseNameByClassID(Nullable<int> classID, string courseName)
        {
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(int));
    
            var courseNameParameter = courseName != null ?
                new ObjectParameter("CourseName", courseName) :
                new ObjectParameter("CourseName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCourseNameByClassID", classIDParameter, courseNameParameter);
        }
    
        public virtual int UpdateCourseNumberByClassID(Nullable<int> classID, Nullable<short> courseNumber)
        {
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(int));
    
            var courseNumberParameter = courseNumber.HasValue ?
                new ObjectParameter("CourseNumber", courseNumber) :
                new ObjectParameter("CourseNumber", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCourseNumberByClassID", classIDParameter, courseNumberParameter);
        }
    
        public virtual int UpdateDisplayFNameByUserID(Nullable<int> userID, string displayFName)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var displayFNameParameter = displayFName != null ?
                new ObjectParameter("DisplayFName", displayFName) :
                new ObjectParameter("DisplayFName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDisplayFNameByUserID", userIDParameter, displayFNameParameter);
        }
    
        public virtual int UpdateDisplayLNameByUserID(Nullable<int> userID, string displayLName)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var displayLNameParameter = displayLName != null ?
                new ObjectParameter("DisplayLName", displayLName) :
                new ObjectParameter("DisplayLName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDisplayLNameByUserID", userIDParameter, displayLNameParameter);
        }
    
        public virtual int UpdateEmailAddressByUserID(Nullable<int> userID, string emailAddress)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateEmailAddressByUserID", userIDParameter, emailAddressParameter);
        }
    
        public virtual int UpdateMentorNameByMentorID(Nullable<int> mentorID, string organizationName)
        {
            var mentorIDParameter = mentorID.HasValue ?
                new ObjectParameter("MentorID", mentorID) :
                new ObjectParameter("MentorID", typeof(int));
    
            var organizationNameParameter = organizationName != null ?
                new ObjectParameter("OrganizationName", organizationName) :
                new ObjectParameter("OrganizationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMentorNameByMentorID", mentorIDParameter, organizationNameParameter);
        }
    
        public virtual int UpdateMessageByMessageID(Nullable<int> messageID, string messageData)
        {
            var messageIDParameter = messageID.HasValue ?
                new ObjectParameter("MessageID", messageID) :
                new ObjectParameter("MessageID", typeof(int));
    
            var messageDataParameter = messageData != null ?
                new ObjectParameter("MessageData", messageData) :
                new ObjectParameter("MessageData", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMessageByMessageID", messageIDParameter, messageDataParameter);
        }
    
        public virtual int UpdatePrivilegesByUserID(Nullable<int> userID, Nullable<int> privileges)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var privilegesParameter = privileges.HasValue ?
                new ObjectParameter("Privileges", privileges) :
                new ObjectParameter("Privileges", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePrivilegesByUserID", userIDParameter, privilegesParameter);
        }
    
        public virtual int UpdateProfilePicture(Nullable<int> userID, byte[] photo)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var photoParameter = photo != null ?
                new ObjectParameter("Photo", photo) :
                new ObjectParameter("Photo", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateProfilePicture", userIDParameter, photoParameter);
        }
    
        public virtual int UpdateReviewDescriptionByReviewID(Nullable<int> reviewID, string description)
        {
            var reviewIDParameter = reviewID.HasValue ?
                new ObjectParameter("ReviewID", reviewID) :
                new ObjectParameter("ReviewID", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateReviewDescriptionByReviewID", reviewIDParameter, descriptionParameter);
        }
    
        public virtual int UpdateServerAdmin(Nullable<int> serverAdminID, string firstName, string lastName, string password, string salt)
        {
            var serverAdminIDParameter = serverAdminID.HasValue ?
                new ObjectParameter("ServerAdminID", serverAdminID) :
                new ObjectParameter("ServerAdminID", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var saltParameter = salt != null ?
                new ObjectParameter("Salt", salt) :
                new ObjectParameter("Salt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateServerAdmin", serverAdminIDParameter, firstNameParameter, lastNameParameter, passwordParameter, saltParameter);
        }
    
        public virtual int UpdateStarRankingByReviewID(Nullable<int> reviewID, Nullable<byte> starRanking)
        {
            var reviewIDParameter = reviewID.HasValue ?
                new ObjectParameter("ReviewID", reviewID) :
                new ObjectParameter("ReviewID", typeof(int));
    
            var starRankingParameter = starRanking.HasValue ?
                new ObjectParameter("StarRanking", starRanking) :
                new ObjectParameter("StarRanking", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStarRankingByReviewID", reviewIDParameter, starRankingParameter);
        }
    
        public virtual int UpdateStickerByChatID(Nullable<int> chatID, Nullable<int> stickerID)
        {
            var chatIDParameter = chatID.HasValue ?
                new ObjectParameter("ChatID", chatID) :
                new ObjectParameter("ChatID", typeof(int));
    
            var stickerIDParameter = stickerID.HasValue ?
                new ObjectParameter("StickerID", stickerID) :
                new ObjectParameter("StickerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStickerByChatID", chatIDParameter, stickerIDParameter);
        }
    
        public virtual int UpdateStickerProblemDescriptionByStickerID(Nullable<int> stickerID, string problemDescription)
        {
            var stickerIDParameter = stickerID.HasValue ?
                new ObjectParameter("StickerID", stickerID) :
                new ObjectParameter("StickerID", typeof(int));
    
            var problemDescriptionParameter = problemDescription != null ?
                new ObjectParameter("ProblemDescription", problemDescription) :
                new ObjectParameter("ProblemDescription", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStickerProblemDescriptionByStickerID", stickerIDParameter, problemDescriptionParameter);
        }
    
        public virtual int UpdateTimeoutByStickerIDAndSeconds(Nullable<int> stickerID, Nullable<int> seconds)
        {
            var stickerIDParameter = stickerID.HasValue ?
                new ObjectParameter("StickerID", stickerID) :
                new ObjectParameter("StickerID", typeof(int));
    
            var secondsParameter = seconds.HasValue ?
                new ObjectParameter("Seconds", seconds) :
                new ObjectParameter("Seconds", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTimeoutByStickerIDAndSeconds", stickerIDParameter, secondsParameter);
        }
    
        public virtual int UpdateTutorIDByTutorIDAndStickerID(Nullable<int> tutorID, Nullable<int> stickerID)
        {
            var tutorIDParameter = tutorID.HasValue ?
                new ObjectParameter("TutorID", tutorID) :
                new ObjectParameter("TutorID", typeof(int));
    
            var stickerIDParameter = stickerID.HasValue ?
                new ObjectParameter("StickerID", stickerID) :
                new ObjectParameter("StickerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTutorIDByTutorIDAndStickerID", tutorIDParameter, stickerIDParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> UpdateUserAverageRank(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("UpdateUserAverageRank", userIDParameter);
        }
    
        public virtual int UpdateUserPasswordByUserID(Nullable<int> userID, string userPassword)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var userPasswordParameter = userPassword != null ?
                new ObjectParameter("UserPassword", userPassword) :
                new ObjectParameter("UserPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUserPasswordByUserID", userIDParameter, userPasswordParameter);
        }
    
        public virtual ObjectResult<UpdateUserTotalReviews_Result> UpdateUserTotalReviews(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UpdateUserTotalReviews_Result>("UpdateUserTotalReviews", userIDParameter);
        }
    
        public virtual ObjectResult<ViewAllUsers_Result> ViewAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewAllUsers_Result>("ViewAllUsers");
        }
    
        public virtual ObjectResult<ViewClasses_Result> ViewClasses(Nullable<int> classID)
        {
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewClasses_Result>("ViewClasses", classIDParameter);
        }
    }
}
