//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnstuckMEUserGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Database
    {
        public int DatabaseID { get; set; }
        public int SchoolID { get; set; }
        public string DatabaseName { get; set; }
        public string DatabaseIP { get; set; }
        public string DatabaseAdminUsername { get; set; }
        public Nullable<bool> DatabaseUsingWindowsAuthen { get; set; }
    
        public virtual School School { get; set; }
    }
}
