//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnstuckMEUserGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolLogo
    {
        public int LogoID { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        public virtual School School { get; set; }
    }
}
