//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnstuckMEUserGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        public int ServerID { get; set; }
        public int SchoolID { get; set; }
        public string ServerDomain { get; set; }
        public string ServerName { get; set; }
        public string ServerIPAddress { get; set; }
    
        public virtual School School { get; set; }
    }
}
