USE UnstuckME_Schools;
GO

IF OBJECT_ID('SchoolLogo', 'U') IS NOT NULL
	DROP TABLE SchoolLogo;
IF OBJECT_ID('Server', 'U') IS NOT NULL
	DROP TABLE [Server];
IF OBJECT_ID('School', 'U') IS NOT NULL
	DROP TABLE School;

CREATE TABLE School
	(SchoolID			INT				PRIMARY KEY IDENTITY(1,1),
	SchoolName 			NVARCHAR(128)	NOT NULL,
	EmailCredentials	VARCHAR(64)		DEFAULT NULL)
 GO

 CREATE TABLE [Server]
	(ServerID			INT				PRIMARY KEY IDENTITY(1,1),
	SchoolID			INT				NOT NULL REFERENCES School(SchoolID),
	ServerDomain		VARCHAR			DEFAULT NULL,
	ServerName			NVARCHAR(128)	NOT NULL UNIQUE,
	ServerIPAddress		VARCHAR(39)		NOT NULL UNIQUE)
GO

CREATE TABLE SchoolLogo
	(LogoID		INT		NOT NULL UNIQUE REFERENCES School(SchoolID),
	Logo		VARBINARY(MAX)
	PRIMARY KEY(LogoID))
GO